### ISSUE TITLE
Some $ref values are not found during the conversion even if they are defined.

### ISSUE THREAD

**Issue by numbbbbb** [samchon/openapi#104]
The example swagger [file](https://api.semanticscholar.org/graph/v1/swagger.json).

Check the output of `OpenApi.convert(swagger).paths`, you can see there are still `$ref` in it. Not sure if it's a bug or expected behavior.

**Comment by samchon** [comment]
I'll test the file.

**Comment by numbbbbb** [comment]
Probably related to the logic [here](https://github.com/samchon/openapi/blob/2ccc87fea8683415288396d4aed7e87a916bf920/src/converters/SwaggerV2Upgrader.ts#L298). Especially this [line](https://github.com/samchon/openapi/blob/2ccc87fea8683415288396d4aed7e87a916bf920/src/converters/SwaggerV2Upgrader.ts#L308), if `schema` is a string spread it with `...schema` seems weird.

**Comment by samchon** [comment]
Found that v3.1 converted OpenAPI document has the `#/definitions/AuthorWithPapers` like reference as you've mentioned.

I'll fix it ASAP.

**Comment by samchon** [comment]
I had not checked the `allOf` case. This is the reason of the bug.

**Comment by numbbbbb** [comment]
Thanks a lot!

**Comment by samchon** [comment]
[semanticscholar.json](https://github.com/user-attachments/files/18003350/semanticscholar.json)

Succeeded to fix the bug, and would be published to `v2.0.1` soon.

**Comment by samchon** [comment]
Upgrade to 2.0.1 version please.

**Comment by numbbbbb** [comment]
I feel like the `2.0.1` introduced more issues related to `$ref`.

To reproduce:

```
const swagger =
	await fetch(
		"https://api.semanticscholar.org/graph/v1/swagger.json",
	).then((r) => r.json()).then(a => {
		console.log(a);

		return a;
	});

const document = OpenApi.convert(swagger);
console.log(JSON.stringify(document));
```

I've attached the result. You can see it sill has many `$ref` in it.

[result.json](https://github.com/user-attachments/files/18008150/result.json)

**Comment by samchon** [comment]
I enhanced the test function about this issue by composing `IHttpLlmApplication` by the Swagger v2 document. And no error had reported during the LLM function calling schema composition.

What is the problem point? Can you point a detailed accessor of it? 

If what you want is erasing `$ref` properties during the `OpenApi.IDocument` conversion, I think it is not proper approach. No reason to escape `$ref` type in the `OpenApi.IDocument` type conversion. Instead, if what you want to is to composing an LLM function calling schema erasing from every `$ref` type like `Google Gemini` case, and you can accomplish it like below:

```typescript
const swagger: SwaggerV2.IDocument = {...};
const document: OpenApi.IDocument = OpenApi.convert(swagger);
const app: IHttpLlmApplication<"gemini"> = HttpLlm.application({
  model: "gemini",
  document,
});
TestValidator.equals("errors")(app.errors.length)(0);
```

**Comment by numbbbbb** [comment]
Thanks @samchon! That makes sense.

Let me explain the feature I'm working on and hopefully get some insights from you.

What I'm trying to do in my project:
1. convert any source OpenAPI JSON to the normalized OpenAPI 3.1.0, this step is already supported by your project
2. extract and store the APIs into a database, for now I'll store each entry in the `document.paths`
3. when I need to use one API, I'll get it from the database and convert it to a function call parameter for a target model

The challenge is that I don't want to store the full `document` in the database which is too large and hard to modify. But if I only store the `document.paths` the `$ref` init won't work because schemas are not stored.

So the solution I have right now is:
1. replace all `$ref` with the real schema so each API path object in the database has everything it needs and don't rely on the schemas
2. when I need an API, I'll wrap the individual `path` object I get from the database to make it looks like a complete OpenAPI 3.1.0 object. Then use `HttpLlm.application()` to get the function call parameters

Seems like I can't erase `$ref` from the `OpenApi.IDocument` for now. So probably I need to store the schemas somewhere and combine it with individual API path before calling `HttpLlm.application()`. It's doable but if you have a better solution please let me know.

**Comment by samchon** [comment]
Then collect only referenced components.schemas for each operation through `OpenApiTypeChecker` module's `visit` and `isReference` functions.

https://github.com/samchon/openapi/blob/master/src/utils/OpenApiTypeChecker.ts

**Comment by numbbbbb** [comment]
Thanks! I'll take a look.
