### ISSUE TITLE
Build fails because it is parsed with $ symbol if URL has a reserved word

### ISSUE THREAD

**Issue by kakasoo** [samchon/openapi#116]
Hello, our great leader, Samchon. In the swagger document I made, 'export' is included in the path name, which is inferred to be false in the above code regular expression and thus causes an error. I am failing to create the lm scheme because of this. I will change the export of the pattern name to exports first. Therefore, this problem is of a solvable nature, but I am sharing it just in case

https://github.com/samchon/openapi/blob/5548c647e74ea5a332a51c60cfb9f23eb02a399d/src/composers/HttpLlmApplicationComposer.ts#L176

```json
{
    ...
    "/connector/google-slides/presentations/{id}/export/hanshow": {}
    ...
}
```

- connector_google_slides_presentations_export_hanshow (What I expected)
- connector_google_slides_presentations_$export_hanshow (result I received)

**Comment by samchon** [comment]
It is the rule of ChatGPT.

I should replace every `$` characters to another thing (`_`) for this case.
